# Generated by Django 5.1.4 on 2025-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('cost_per_night', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=100)),
                ('cost_per_day', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('districts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('petrol_price', models.FloatField()),
                ('fuel_efficiency', models.FloatField()),
                ('total_cost', models.FloatField()),
            ],
        ),
    ]
